<?php
/**
 * Helper functions for the "Table of Contents" block: collects the
 * core/heading blocks from a post's content and stamps each rendered heading
 * with a matching anchor, mirroring the outline panel shown in a Google Doc.
 *
 * @package Blockfolio
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Returns the heading text/level for a "blockfolio/work-experience" or
 * "blockfolio/work-experience-item" block — neither renders a core/heading
 * block, so they need their own text extraction — or null for any other
 * block. Shared by the collector below and blockfolio_add_heading_anchor()
 * so both stay in sync on which block instances actually produce a heading.
 *
 * @param array $block Parsed block data.
 * @return array{text: string, level: int}|null
 */
function blockfolio_get_custom_heading( $block ) {
	if ( 'blockfolio/work-experience' === $block['blockName'] ) {
		return array(
			'text'  => trim( wp_strip_all_tags( $block['attrs']['title'] ?? 'Work Experience' ) ),
			'level' => 2,
		);
	}

	if ( 'blockfolio/work-experience-item' === $block['blockName'] ) {
		return array(
			'text'  => trim( wp_strip_all_tags( $block['attrs']['role'] ?? '' ) ),
			'level' => 3,
		);
	}

	return null;
}

/**
 * Collects the core/heading blocks (including ones inside patterns and
 * template parts) from a post's content — or, on the front page when it has
 * no singular post behind it (e.g. "Your homepage displays: your latest
 * posts"), from the front-page block template instead — and assigns each
 * one a unique anchor slug, mirroring the outline panel shown in a Google Doc.
 *
 * @param int|null $post_id Post ID. Defaults to the current post.
 * @return array[] List of headings, each with "level", "text" and "anchor".
 */
function blockfolio_get_post_headings( $post_id = null ) {
	static $cache = array();

	$post_id   = $post_id ? (int) $post_id : get_the_ID();
	$cache_key = $post_id ? $post_id : 'front-page';

	if ( isset( $cache[ $cache_key ] ) ) {
		return $cache[ $cache_key ];
	}

	if ( $post_id ) {
		$post = get_post( $post_id );

		if ( ! $post ) {
			return array();
		}

		$content = $post->post_content;
	} elseif ( is_front_page() ) {
		$template = get_block_template( get_stylesheet() . '//front-page', 'wp_template' );

		if ( ! $template ) {
			return array();
		}

		$content = $template->content;
	} else {
		return array();
	}

	$headings = array();
	$slugs    = array();

	$collect = function ( $blocks ) use ( &$collect, &$headings, &$slugs ) {
		foreach ( $blocks as $block ) {
			// Patterns and template parts aren't inlined in the stored markup,
			// so resolve them to look inside for headings too.
			if ( 'core/pattern' === $block['blockName'] && ! empty( $block['attrs']['slug'] ) ) {
				$pattern = WP_Block_Patterns_Registry::get_instance()->get_registered( $block['attrs']['slug'] );

				if ( $pattern ) {
					$collect( parse_blocks( $pattern['content'] ) );
				}

				continue;
			}

			if ( 'core/template-part' === $block['blockName'] && ! empty( $block['attrs']['slug'] ) ) {
				$theme = $block['attrs']['theme'] ?? get_stylesheet();
				$part  = get_block_template( $theme . '//' . $block['attrs']['slug'], 'wp_template_part' );

				if ( $part ) {
					$collect( parse_blocks( $part->content ) );
				}

				continue;
			}

			// The "Work Experience"/"Education" title and each item's role are
			// real h2/h3 tags but aren't core/heading blocks.
			$custom_heading = blockfolio_get_custom_heading( $block );

			if ( 'core/heading' === $block['blockName'] || null !== $custom_heading ) {
				if ( null !== $custom_heading ) {
					$text  = $custom_heading['text'];
					$level = $custom_heading['level'];
				} else {
					$text  = trim( wp_strip_all_tags( $block['innerHTML'] ) );
					$level = isset( $block['attrs']['level'] ) ? (int) $block['attrs']['level'] : 2;
				}

				if ( '' !== $text ) {
					$slug = ! empty( $block['attrs']['anchor'] ) ? $block['attrs']['anchor'] : sanitize_title( $text );
					$base = $slug;
					$n    = 2;

					while ( isset( $slugs[ $slug ] ) ) {
						$slug = $base . '-' . $n++;
					}

					$slugs[ $slug ] = true;

					$headings[] = array(
						'level'  => $level,
						'text'   => $text,
						'anchor' => $slug,
					);
				}
			}

			if ( ! empty( $block['innerBlocks'] ) ) {
				$collect( $block['innerBlocks'] );
			}
		}
	};

	$collect( parse_blocks( $content ) );

	$cache[ $cache_key ] = $headings;

	return $headings;
}

/**
 * Stamps each rendered heading block with the anchor generated by
 * blockfolio_get_post_headings(), so the table of contents can link to it.
 *
 * @param string $block_content Rendered block HTML.
 * @param array  $block         Parsed block data.
 * @return string
 */
function blockfolio_add_heading_anchor( $block_content, $block ) {
	if ( ! is_singular() && ! is_front_page() ) {
		return $block_content;
	}

	static $index    = 0;
	static $for_post = null;

	$post_id = get_the_ID();

	if ( $for_post !== $post_id ) {
		$for_post = $post_id;
		$index    = 0;
	}

	$headings = blockfolio_get_post_headings( $post_id );

	if ( 'blockfolio/work-experience' === $block['blockName'] ) {
		// WordPress renders a block's children before the block itself, so
		// by now this section's "work-experience-item" children are already
		// rendered inside $block_content. Stamping them via their own filter
		// would consume headings in that child-before-parent render order
		// instead of the parent-before-children order used by the TOC list,
		// so stamp the section's own title and all of its items' roles here
		// together, in one left-to-right pass over the same content.
		$custom_heading = blockfolio_get_custom_heading( $block );

		if ( '' === $custom_heading['text'] || ! isset( $headings[ $index ] ) ) {
			return $block_content;
		}

		$tags = new WP_HTML_Tag_Processor( $block_content );

		if ( ! $tags->next_tag( array( 'tag_name' => 'h2', 'class_name' => 'blockfolio-work-experience__title' ) ) ) {
			return $block_content;
		}

		$tags->set_attribute( 'id', $headings[ $index ]['anchor'] );
		++$index;

		while ( isset( $headings[ $index ] ) && $tags->next_tag( array( 'tag_name' => 'h3', 'class_name' => 'blockfolio-work-experience-item__role' ) ) ) {
			$tags->set_attribute( 'id', $headings[ $index ]['anchor'] );
			++$index;
		}

		return $tags->get_updated_html();
	}

	if ( '' === trim( wp_strip_all_tags( $block_content ) ) ) {
		return $block_content;
	}

	if ( ! isset( $headings[ $index ] ) ) {
		return $block_content;
	}

	$anchor = $headings[ $index ]['anchor'];
	++$index;

	$tags = new WP_HTML_Tag_Processor( $block_content );

	if ( $tags->next_tag() ) {
		$tags->set_attribute( 'id', $anchor );
	}

	return $tags->get_updated_html();
}
add_filter( 'render_block_core/heading', 'blockfolio_add_heading_anchor', 10, 2 );
add_filter( 'render_block_blockfolio/work-experience', 'blockfolio_add_heading_anchor', 10, 2 );
